# File for noice errors generation

Name = "mcErrors"
SID = 12

# errors
[[error]]
    Name = "ErrUnableToConvert"
    StatusHTTP = 400
    Message = "Unable to convert resource"
    Kind = 1

[[error]]
    Name = "ErrInternalError"
    StatusHTTP = 500
    Message = "Internal error"
    Kind = 2